"""add_zone_feedback

Revision ID: c7d92b5ede19
Revises: 001
Create Date: 2026-02-09 17:43:38.428163+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'c7d92b5ede19'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zone_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_zone_id', sa.UUID(), nullable=False),
    sa.Column('roofer_account_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('visible_damage', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('zone_score_at_feedback', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_zone_id'], ['lead_zones.id'], ),
    sa.ForeignKeyConstraint(['roofer_account_id'], ['roofer_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_zone_id', 'roofer_account_id', name='uq_zone_feedback_zone_roofer')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zone_feedback')
    # ### end Alembic commands ###
